/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.bdd.xtext.BddDslRuntimeModule;
import dk.sdu.bdd.xtext.BddDslStandaloneSetup;
import dk.sdu.bdd.xtext.ide.BddDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class BddDslWebSetup extends BddDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    BddDslRuntimeModule _bddDslRuntimeModule = new BddDslRuntimeModule();
    BddDslIdeModule _bddDslIdeModule = new BddDslIdeModule();
    BddDslWebModule _bddDslWebModule = new BddDslWebModule();
    return Guice.createInjector(Modules2.mixin(_bddDslRuntimeModule, _bddDslIdeModule, _bddDslWebModule));
  }
}
