/*
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dk.sdu.bdd.xtext.ide.contentassist.antlr.internal.InternalBddDslParser;
import dk.sdu.bdd.xtext.services.BddDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class BddDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BddDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BddDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getAlternatives_1(), "rule__Model__Alternatives_1");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getNameAlternatives_2_0(), "rule__DeclarativeEntityDef__NameAlternatives_2_0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getAlternatives_7_4_0(), "rule__DeclarativeEntityDef__Alternatives_7_4_0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getAlternatives_8_4_0(), "rule__DeclarativeEntityDef__Alternatives_8_4_0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getNameAlternatives_2_0(), "rule__ImperativeEntityDef__NameAlternatives_2_0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getAlternatives_7_4_0(), "rule__ImperativeEntityDef__Alternatives_7_4_0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getAlternatives_8_4_0(), "rule__ImperativeEntityDef__Alternatives_8_4_0");
			builder.put(grammarAccess.getPREPAccess().getAlternatives(), "rule__PREP__Alternatives");
			builder.put(grammarAccess.getStateNameAccess().getAlternatives_1(), "rule__StateName__Alternatives_1");
			builder.put(grammarAccess.getID_OR_STRINGAccess().getAlternatives(), "rule__ID_OR_STRING__Alternatives");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_2(), "rule__Scenario__Alternatives_2");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_4(), "rule__Scenario__Alternatives_4");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_6(), "rule__Scenario__Alternatives_6");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_8(), "rule__Scenario__Alternatives_8");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_10(), "rule__Scenario__Alternatives_10");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_10_0_0(), "rule__Scenario__Alternatives_10_0_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_10_1_1(), "rule__Scenario__Alternatives_10_1_1");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12(), "rule__Scenario__Alternatives_12");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_0_0(), "rule__Scenario__Alternatives_12_0_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_12_1_0(), "rule__Scenario__Alternatives_12_1_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_14(), "rule__Scenario__Alternatives_14");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_14_0_0(), "rule__Scenario__Alternatives_14_0_0");
			builder.put(grammarAccess.getScenarioAccess().getAlternatives_14_1_1(), "rule__Scenario__Alternatives_14_1_1");
			builder.put(grammarAccess.getDeclarativeStatePhraseAccess().getAlternatives(), "rule__DeclarativeStatePhrase__Alternatives");
			builder.put(grammarAccess.getImperativeStatePhraseAccess().getAlternatives(), "rule__ImperativeStatePhrase__Alternatives");
			builder.put(grammarAccess.getENTITY_IDENTITYAccess().getAlternatives(), "rule__ENTITY_IDENTITY__Alternatives");
			builder.put(grammarAccess.getOPTIONAccess().getAlternatives_1(), "rule__OPTION__Alternatives_1");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getAlternatives(), "rule__DeclarativeEntityRef__Alternatives");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getAlternatives_0_1(), "rule__DeclarativeEntityRef__Alternatives_0_1");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getAlternatives_0_2_0(), "rule__DeclarativeEntityRef__Alternatives_0_2_0");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getAlternatives_0_1(), "rule__DeclarativeEntityStatePhrase__Alternatives_0_1");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getAlternatives_0_3(), "rule__DeclarativeEntityStatePhrase__Alternatives_0_3");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getAlternatives_0_4(), "rule__DeclarativeEntityStatePhrase__Alternatives_0_4");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getAlternatives_2(), "rule__DeclarativeEntityStatePhrase__Alternatives_2");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getAlternatives_1(), "rule__DeclarativeEntityPropertyStatePhrase__Alternatives_1");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getAlternatives_3(), "rule__DeclarativeEntityPropertyStatePhrase__Alternatives_3");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getAlternatives_5(), "rule__DeclarativeEntityPropertyStatePhrase__Alternatives_5");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getAlternatives_5_0_0_0(), "rule__DeclarativeEntityPropertyStatePhrase__Alternatives_5_0_0_0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getAlternatives_5_1_0(), "rule__DeclarativeEntityPropertyStatePhrase__Alternatives_5_1_0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getAlternatives_5_1_0_0_0(), "rule__DeclarativeEntityPropertyStatePhrase__Alternatives_5_1_0_0_0");
			builder.put(grammarAccess.getImperativeEntityPropertyStatePhraseAccess().getAlternatives_2(), "rule__ImperativeEntityPropertyStatePhrase__Alternatives_2");
			builder.put(grammarAccess.getSimpleValueAccess().getAlternatives(), "rule__SimpleValue__Alternatives");
			builder.put(grammarAccess.getDeclarativeActionPhraseAccess().getAlternatives(), "rule__DeclarativeActionPhrase__Alternatives");
			builder.put(grammarAccess.getVerbActionAccess().getAlternatives_5(), "rule__VerbAction__Alternatives_5");
			builder.put(grammarAccess.getVerbActionAccess().getAlternatives_7(), "rule__VerbAction__Alternatives_7");
			builder.put(grammarAccess.getVerbActionAccess().getAlternatives_9(), "rule__VerbAction__Alternatives_9");
			builder.put(grammarAccess.getVerbActionAccess().getAlternatives_10(), "rule__VerbAction__Alternatives_10");
			builder.put(grammarAccess.getDeclarativeActionRefAccess().getAlternatives_4_0(), "rule__DeclarativeActionRef__Alternatives_4_0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0(), "rule__Model__Group_0__0");
			builder.put(grammarAccess.getModelRefAccess().getGroup(), "rule__ModelRef__Group__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup(), "rule__DeclarativeEntityDef__Group__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_3(), "rule__DeclarativeEntityDef__Group_3__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_4(), "rule__DeclarativeEntityDef__Group_4__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_4_2(), "rule__DeclarativeEntityDef__Group_4_2__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_6(), "rule__DeclarativeEntityDef__Group_6__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_6_2(), "rule__DeclarativeEntityDef__Group_6_2__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_7(), "rule__DeclarativeEntityDef__Group_7__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_7_3(), "rule__DeclarativeEntityDef__Group_7_3__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_7_4(), "rule__DeclarativeEntityDef__Group_7_4__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_8(), "rule__DeclarativeEntityDef__Group_8__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_8_3(), "rule__DeclarativeEntityDef__Group_8_3__0");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getGroup_8_4(), "rule__DeclarativeEntityDef__Group_8_4__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup(), "rule__ImperativeEntityDef__Group__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_3(), "rule__ImperativeEntityDef__Group_3__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_4(), "rule__ImperativeEntityDef__Group_4__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_4_2(), "rule__ImperativeEntityDef__Group_4_2__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_6(), "rule__ImperativeEntityDef__Group_6__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_6_2(), "rule__ImperativeEntityDef__Group_6_2__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_7(), "rule__ImperativeEntityDef__Group_7__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_7_3(), "rule__ImperativeEntityDef__Group_7_3__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_7_4(), "rule__ImperativeEntityDef__Group_7_4__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_8(), "rule__ImperativeEntityDef__Group_8__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_8_3(), "rule__ImperativeEntityDef__Group_8_3__0");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getGroup_8_4(), "rule__ImperativeEntityDef__Group_8_4__0");
			builder.put(grammarAccess.getImperativeActionDefAccess().getGroup(), "rule__ImperativeActionDef__Group__0");
			builder.put(grammarAccess.getActionDefAccess().getGroup(), "rule__ActionDef__Group__0");
			builder.put(grammarAccess.getStateDefAccess().getGroup(), "rule__StateDef__Group__0");
			builder.put(grammarAccess.getStateDefAccess().getGroup_2(), "rule__StateDef__Group_2__0");
			builder.put(grammarAccess.getStateNameAccess().getGroup(), "rule__StateName__Group__0");
			builder.put(grammarAccess.getStateNameAccess().getGroup_1_0(), "rule__StateName__Group_1_0__0");
			builder.put(grammarAccess.getStateNameAccess().getGroup_1_1(), "rule__StateName__Group_1_1__0");
			builder.put(grammarAccess.getPropertyDefAccess().getGroup(), "rule__PropertyDef__Group__0");
			builder.put(grammarAccess.getImperativeStateDefAccess().getGroup(), "rule__ImperativeStateDef__Group__0");
			builder.put(grammarAccess.getImperativeStateDefAccess().getGroup_2(), "rule__ImperativeStateDef__Group_2__0");
			builder.put(grammarAccess.getImperativePropertyDefAccess().getGroup(), "rule__ImperativePropertyDef__Group__0");
			builder.put(grammarAccess.getImperativeScenarioAccess().getGroup(), "rule__ImperativeScenario__Group__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup(), "rule__Scenario__Group__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_2_6(), "rule__Scenario__Group_2_6__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_10_0(), "rule__Scenario__Group_10_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_10_0_0_0(), "rule__Scenario__Group_10_0_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_10_0_0_1(), "rule__Scenario__Group_10_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_10_0_1(), "rule__Scenario__Group_10_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_10_1(), "rule__Scenario__Group_10_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_10_1_1_1(), "rule__Scenario__Group_10_1_1_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_10_1_2(), "rule__Scenario__Group_10_1_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0(), "rule__Scenario__Group_12_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_0(), "rule__Scenario__Group_12_0_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_1(), "rule__Scenario__Group_12_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_0_3(), "rule__Scenario__Group_12_0_0_3__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_0_1(), "rule__Scenario__Group_12_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1(), "rule__Scenario__Group_12_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_0_0(), "rule__Scenario__Group_12_1_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_0_1(), "rule__Scenario__Group_12_1_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_0_2(), "rule__Scenario__Group_12_1_0_2__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_12_1_0_3(), "rule__Scenario__Group_12_1_0_3__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_14_0(), "rule__Scenario__Group_14_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_14_0_0_0(), "rule__Scenario__Group_14_0_0_0__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_14_0_0_1(), "rule__Scenario__Group_14_0_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_14_0_1(), "rule__Scenario__Group_14_0_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_14_1(), "rule__Scenario__Group_14_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_14_1_1_1(), "rule__Scenario__Group_14_1_1_1__0");
			builder.put(grammarAccess.getScenarioAccess().getGroup_14_1_2(), "rule__Scenario__Group_14_1_2__0");
			builder.put(grammarAccess.getDeclarativeScenarioStateAccess().getGroup(), "rule__DeclarativeScenarioState__Group__0");
			builder.put(grammarAccess.getDeclarativeScenarioStateAccess().getGroup_1(), "rule__DeclarativeScenarioState__Group_1__0");
			builder.put(grammarAccess.getImperativeScenarioStateAccess().getGroup(), "rule__ImperativeScenarioState__Group__0");
			builder.put(grammarAccess.getImperativeScenarioStateAccess().getGroup_1(), "rule__ImperativeScenarioState__Group_1__0");
			builder.put(grammarAccess.getDeclarativeScenarioActionAccess().getGroup(), "rule__DeclarativeScenarioAction__Group__0");
			builder.put(grammarAccess.getDeclarativeScenarioActionAccess().getGroup_1(), "rule__DeclarativeScenarioAction__Group_1__0");
			builder.put(grammarAccess.getImperativeScenarioActionAccess().getGroup(), "rule__ImperativeScenarioAction__Group__0");
			builder.put(grammarAccess.getImperativeScenarioActionAccess().getGroup_1(), "rule__ImperativeScenarioAction__Group_1__0");
			builder.put(grammarAccess.getENTITY_IDENTITYAccess().getGroup_0(), "rule__ENTITY_IDENTITY__Group_0__0");
			builder.put(grammarAccess.getOPTIONAccess().getGroup(), "rule__OPTION__Group__0");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getGroup_0(), "rule__DeclarativeEntityRef__Group_0__0");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getGroup_0_0(), "rule__DeclarativeEntityRef__Group_0_0__0");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getGroup_0_2(), "rule__DeclarativeEntityRef__Group_0_2__0");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getGroup_0_2_0_1(), "rule__DeclarativeEntityRef__Group_0_2_0_1__0");
			builder.put(grammarAccess.getImperativeEntityRefAccess().getGroup(), "rule__ImperativeEntityRef__Group__0");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getGroup(), "rule__DeclarativeEntityStatePhrase__Group__0");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getGroup_0(), "rule__DeclarativeEntityStatePhrase__Group_0__0");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getGroup_0_1_1(), "rule__DeclarativeEntityStatePhrase__Group_0_1_1__0");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getGroup_0_3_1(), "rule__DeclarativeEntityStatePhrase__Group_0_3_1__0");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getGroup_0_4_1(), "rule__DeclarativeEntityStatePhrase__Group_0_4_1__0");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getGroup_0_4_2(), "rule__DeclarativeEntityStatePhrase__Group_0_4_2__0");
			builder.put(grammarAccess.getImperativeEntityStatePhraseAccess().getGroup(), "rule__ImperativeEntityStatePhrase__Group__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup(), "rule__DeclarativeEntityPropertyStatePhrase__Group__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_1_1(), "rule__DeclarativeEntityPropertyStatePhrase__Group_1_1__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_3_3(), "rule__DeclarativeEntityPropertyStatePhrase__Group_3_3__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_3_4(), "rule__DeclarativeEntityPropertyStatePhrase__Group_3_4__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_5_0(), "rule__DeclarativeEntityPropertyStatePhrase__Group_5_0__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_5_0_0(), "rule__DeclarativeEntityPropertyStatePhrase__Group_5_0_0__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_5_0_0_0_1(), "rule__DeclarativeEntityPropertyStatePhrase__Group_5_0_0_0_1__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_5_1(), "rule__DeclarativeEntityPropertyStatePhrase__Group_5_1__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_5_1_0_0(), "rule__DeclarativeEntityPropertyStatePhrase__Group_5_1_0_0__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_5_1_0_0_0_1(), "rule__DeclarativeEntityPropertyStatePhrase__Group_5_1_0_0_0_1__0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getGroup_5_1_0_1(), "rule__DeclarativeEntityPropertyStatePhrase__Group_5_1_0_1__0");
			builder.put(grammarAccess.getImperativeEntityPropertyStatePhraseAccess().getGroup(), "rule__ImperativeEntityPropertyStatePhrase__Group__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup(), "rule__VerbAction__Group__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup_4(), "rule__VerbAction__Group_4__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup_5_0(), "rule__VerbAction__Group_5_0__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup_5_3(), "rule__VerbAction__Group_5_3__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup_10_2(), "rule__VerbAction__Group_10_2__0");
			builder.put(grammarAccess.getVerbActionAccess().getGroup_10_3(), "rule__VerbAction__Group_10_3__0");
			builder.put(grammarAccess.getDeclarativeEntityActionAccess().getGroup(), "rule__DeclarativeEntityAction__Group__0");
			builder.put(grammarAccess.getDeclarativeEntityActionAccess().getGroup_2(), "rule__DeclarativeEntityAction__Group_2__0");
			builder.put(grammarAccess.getImperativeEntityActionAccess().getGroup(), "rule__ImperativeEntityAction__Group__0");
			builder.put(grammarAccess.getPropertyRefAccess().getGroup(), "rule__PropertyRef__Group__0");
			builder.put(grammarAccess.getPropertyRefAccess().getGroup_3(), "rule__PropertyRef__Group_3__0");
			builder.put(grammarAccess.getImperativePropertyRefAccess().getGroup(), "rule__ImperativePropertyRef__Group__0");
			builder.put(grammarAccess.getImperativePropertyRefAccess().getGroup_3(), "rule__ImperativePropertyRef__Group_3__0");
			builder.put(grammarAccess.getDeclarativeActionRefAccess().getGroup(), "rule__DeclarativeActionRef__Group__0");
			builder.put(grammarAccess.getDeclarativeActionRefAccess().getGroup_4(), "rule__DeclarativeActionRef__Group_4__0");
			builder.put(grammarAccess.getDOUBLEAccess().getGroup(), "rule__DOUBLE__Group__0");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_0_1(), "rule__Model__NameAssignment_0_1");
			builder.put(grammarAccess.getModelAccess().getModelRefsAssignment_1_0(), "rule__Model__ModelRefsAssignment_1_0");
			builder.put(grammarAccess.getModelAccess().getDeclarativeEntityDefAssignment_1_1(), "rule__Model__DeclarativeEntityDefAssignment_1_1");
			builder.put(grammarAccess.getModelAccess().getImperativeEntityDefAssignment_1_2(), "rule__Model__ImperativeEntityDefAssignment_1_2");
			builder.put(grammarAccess.getModelAccess().getScenariosAssignment_1_3(), "rule__Model__ScenariosAssignment_1_3");
			builder.put(grammarAccess.getModelRefAccess().getModelRefAssignment_1(), "rule__ModelRef__ModelRefAssignment_1");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getNameAssignment_2(), "rule__DeclarativeEntityDef__NameAssignment_2");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getSuperEntitiesAssignment_4_1(), "rule__DeclarativeEntityDef__SuperEntitiesAssignment_4_1");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getSuperEntitiesAssignment_4_2_1(), "rule__DeclarativeEntityDef__SuperEntitiesAssignment_4_2_1");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getActionsAssignment_6_1(), "rule__DeclarativeEntityDef__ActionsAssignment_6_1");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getActionsAssignment_6_2_1(), "rule__DeclarativeEntityDef__ActionsAssignment_6_2_1");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getStatesAssignment_7_1(), "rule__DeclarativeEntityDef__StatesAssignment_7_1");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getStatesAssignment_7_4_1(), "rule__DeclarativeEntityDef__StatesAssignment_7_4_1");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getPropertiesAssignment_8_1(), "rule__DeclarativeEntityDef__PropertiesAssignment_8_1");
			builder.put(grammarAccess.getDeclarativeEntityDefAccess().getPropertiesAssignment_8_4_1(), "rule__DeclarativeEntityDef__PropertiesAssignment_8_4_1");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getNameAssignment_2(), "rule__ImperativeEntityDef__NameAssignment_2");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getSuperEntitiesAssignment_4_1(), "rule__ImperativeEntityDef__SuperEntitiesAssignment_4_1");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getSuperEntitiesAssignment_4_2_1(), "rule__ImperativeEntityDef__SuperEntitiesAssignment_4_2_1");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getActionsAssignment_6_1(), "rule__ImperativeEntityDef__ActionsAssignment_6_1");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getActionsAssignment_6_2_1(), "rule__ImperativeEntityDef__ActionsAssignment_6_2_1");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getStatesAssignment_7_1(), "rule__ImperativeEntityDef__StatesAssignment_7_1");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getStatesAssignment_7_4_1(), "rule__ImperativeEntityDef__StatesAssignment_7_4_1");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getPropertiesAssignment_8_1(), "rule__ImperativeEntityDef__PropertiesAssignment_8_1");
			builder.put(grammarAccess.getImperativeEntityDefAccess().getPropertiesAssignment_8_4_1(), "rule__ImperativeEntityDef__PropertiesAssignment_8_4_1");
			builder.put(grammarAccess.getImperativeActionDefAccess().getNameAssignment_0(), "rule__ImperativeActionDef__NameAssignment_0");
			builder.put(grammarAccess.getActionDefAccess().getNameAssignment_0(), "rule__ActionDef__NameAssignment_0");
			builder.put(grammarAccess.getStateDefAccess().getPostiveAssignment_0(), "rule__StateDef__PostiveAssignment_0");
			builder.put(grammarAccess.getStateDefAccess().getNegativeAssignment_2_1(), "rule__StateDef__NegativeAssignment_2_1");
			builder.put(grammarAccess.getStateNameAccess().getNameAssignment_0(), "rule__StateName__NameAssignment_0");
			builder.put(grammarAccess.getStateNameAccess().getName2Assignment_1_0_1(), "rule__StateName__Name2Assignment_1_0_1");
			builder.put(grammarAccess.getStateNameAccess().getName3Assignment_1_1_1(), "rule__StateName__Name3Assignment_1_1_1");
			builder.put(grammarAccess.getPropertyDefAccess().getNameAssignment_0(), "rule__PropertyDef__NameAssignment_0");
			builder.put(grammarAccess.getPropertyDefAccess().getPluralAssignment_1(), "rule__PropertyDef__PluralAssignment_1");
			builder.put(grammarAccess.getImperativeStateDefAccess().getPostiveAssignment_0(), "rule__ImperativeStateDef__PostiveAssignment_0");
			builder.put(grammarAccess.getImperativeStateDefAccess().getNegativeAssignment_2_1(), "rule__ImperativeStateDef__NegativeAssignment_2_1");
			builder.put(grammarAccess.getImperativeStateNameAccess().getImpStatNameAssignment(), "rule__ImperativeStateName__ImpStatNameAssignment");
			builder.put(grammarAccess.getImperativePropertyDefAccess().getNameAssignment_0(), "rule__ImperativePropertyDef__NameAssignment_0");
			builder.put(grammarAccess.getImperativePropertyDefAccess().getPluralAssignment_1(), "rule__ImperativePropertyDef__PluralAssignment_1");
			builder.put(grammarAccess.getImperativeScenarioAccess().getPreStateAssignment_3(), "rule__ImperativeScenario__PreStateAssignment_3");
			builder.put(grammarAccess.getImperativeScenarioAccess().getActionAssignment_5(), "rule__ImperativeScenario__ActionAssignment_5");
			builder.put(grammarAccess.getImperativeScenarioAccess().getPostStateAssignment_7(), "rule__ImperativeScenario__PostStateAssignment_7");
			builder.put(grammarAccess.getScenarioAccess().getNameAssignment_1(), "rule__Scenario__NameAssignment_1");
			builder.put(grammarAccess.getScenarioAccess().getPreStateEAssignment_10_1_3(), "rule__Scenario__PreStateEAssignment_10_1_3");
			builder.put(grammarAccess.getScenarioAccess().getImperative1Assignment_11(), "rule__Scenario__Imperative1Assignment_11");
			builder.put(grammarAccess.getScenarioAccess().getActionEAssignment_12_1_1(), "rule__Scenario__ActionEAssignment_12_1_1");
			builder.put(grammarAccess.getScenarioAccess().getImperative2Assignment_13(), "rule__Scenario__Imperative2Assignment_13");
			builder.put(grammarAccess.getScenarioAccess().getPreStateE1Assignment_14_1_3(), "rule__Scenario__PreStateE1Assignment_14_1_3");
			builder.put(grammarAccess.getScenarioAccess().getImperative3Assignment_15(), "rule__Scenario__Imperative3Assignment_15");
			builder.put(grammarAccess.getDeclarativeScenarioStateAccess().getStatesAssignment_0(), "rule__DeclarativeScenarioState__StatesAssignment_0");
			builder.put(grammarAccess.getDeclarativeScenarioStateAccess().getStatesAssignment_1_1(), "rule__DeclarativeScenarioState__StatesAssignment_1_1");
			builder.put(grammarAccess.getImperativeScenarioStateAccess().getStatesAssignment_0(), "rule__ImperativeScenarioState__StatesAssignment_0");
			builder.put(grammarAccess.getImperativeScenarioStateAccess().getStatesAssignment_1_1(), "rule__ImperativeScenarioState__StatesAssignment_1_1");
			builder.put(grammarAccess.getDeclarativeScenarioActionAccess().getActionsAssignment_0(), "rule__DeclarativeScenarioAction__ActionsAssignment_0");
			builder.put(grammarAccess.getDeclarativeScenarioActionAccess().getActionsAssignment_1_1(), "rule__DeclarativeScenarioAction__ActionsAssignment_1_1");
			builder.put(grammarAccess.getImperativeScenarioActionAccess().getActionsAssignment_0(), "rule__ImperativeScenarioAction__ActionsAssignment_0");
			builder.put(grammarAccess.getImperativeScenarioActionAccess().getActionsAssignment_1_1(), "rule__ImperativeScenarioAction__ActionsAssignment_1_1");
			builder.put(grammarAccess.getDeclarativeStatePhraseAccess().getEspAssignment_1(), "rule__DeclarativeStatePhrase__EspAssignment_1");
			builder.put(grammarAccess.getImperativeStatePhraseAccess().getEpspAssignment_0(), "rule__ImperativeStatePhrase__EpspAssignment_0");
			builder.put(grammarAccess.getImperativeStatePhraseAccess().getEspAssignment_1(), "rule__ImperativeStatePhrase__EspAssignment_1");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getEntityAssignment_0_2_1(), "rule__DeclarativeEntityRef__EntityAssignment_0_2_1");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getNameAssignment_0_2_2(), "rule__DeclarativeEntityRef__NameAssignment_0_2_2");
			builder.put(grammarAccess.getDeclarativeEntityRefAccess().getNameAssignment_1(), "rule__DeclarativeEntityRef__NameAssignment_1");
			builder.put(grammarAccess.getImperativeEntityRefAccess().getEntityAssignment_1(), "rule__ImperativeEntityRef__EntityAssignment_1");
			builder.put(grammarAccess.getImperativeEntityRefAccess().getNameAssignment_2(), "rule__ImperativeEntityRef__NameAssignment_2");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getPropertyAssignment_0_0(), "rule__DeclarativeEntityStatePhrase__PropertyAssignment_0_0");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getEntityAssignment_1(), "rule__DeclarativeEntityStatePhrase__EntityAssignment_1");
			builder.put(grammarAccess.getDeclarativeEntityStatePhraseAccess().getStateAssignment_4(), "rule__DeclarativeEntityStatePhrase__StateAssignment_4");
			builder.put(grammarAccess.getImperativeEntityStatePhraseAccess().getEntityAssignment_0(), "rule__ImperativeEntityStatePhrase__EntityAssignment_0");
			builder.put(grammarAccess.getImperativeEntityStatePhraseAccess().getStateAssignment_2(), "rule__ImperativeEntityStatePhrase__StateAssignment_2");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getPropertyAssignment_0(), "rule__DeclarativeEntityPropertyStatePhrase__PropertyAssignment_0");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getEntityAssignment_4(), "rule__DeclarativeEntityPropertyStatePhrase__EntityAssignment_4");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getValueAssignment_5_0_0_1(), "rule__DeclarativeEntityPropertyStatePhrase__ValueAssignment_5_0_0_1");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getValuesAssignment_5_1_0_0_1(), "rule__DeclarativeEntityPropertyStatePhrase__ValuesAssignment_5_1_0_0_1");
			builder.put(grammarAccess.getDeclarativeEntityPropertyStatePhraseAccess().getValuesAssignment_5_1_0_1_1(), "rule__DeclarativeEntityPropertyStatePhrase__ValuesAssignment_5_1_0_1_1");
			builder.put(grammarAccess.getImperativeEntityPropertyStatePhraseAccess().getPropertyAssignment_1(), "rule__ImperativeEntityPropertyStatePhrase__PropertyAssignment_1");
			builder.put(grammarAccess.getImperativeEntityPropertyStatePhraseAccess().getEntityAssignment_3(), "rule__ImperativeEntityPropertyStatePhrase__EntityAssignment_3");
			builder.put(grammarAccess.getImperativeEntityPropertyStatePhraseAccess().getPropertyValueAssignment_5(), "rule__ImperativeEntityPropertyStatePhrase__PropertyValueAssignment_5");
			builder.put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
			builder.put(grammarAccess.getIntValueAccess().getValueAssignment(), "rule__IntValue__ValueAssignment");
			builder.put(grammarAccess.getDoubleValueAccess().getValueAssignment(), "rule__DoubleValue__ValueAssignment");
			builder.put(grammarAccess.getVerbActionAccess().getActionAssignment_0(), "rule__VerbAction__ActionAssignment_0");
			builder.put(grammarAccess.getVerbActionAccess().getEntityAssignment_6(), "rule__VerbAction__EntityAssignment_6");
			builder.put(grammarAccess.getVerbActionAccess().getEntity2Assignment_8(), "rule__VerbAction__Entity2Assignment_8");
			builder.put(grammarAccess.getVerbActionAccess().getEntity3Assignment_12(), "rule__VerbAction__Entity3Assignment_12");
			builder.put(grammarAccess.getDeclarativeEntityActionAccess().getEntityActionAssignment_0(), "rule__DeclarativeEntityAction__EntityActionAssignment_0");
			builder.put(grammarAccess.getDeclarativeEntityActionAccess().getActionDefAssignment_1(), "rule__DeclarativeEntityAction__ActionDefAssignment_1");
			builder.put(grammarAccess.getDeclarativeEntityActionAccess().getEntityRefAssignment_3(), "rule__DeclarativeEntityAction__EntityRefAssignment_3");
			builder.put(grammarAccess.getDeclarativeEntityActionAccess().getPropertyRefAssignment_4(), "rule__DeclarativeEntityAction__PropertyRefAssignment_4");
			builder.put(grammarAccess.getImperativeEntityActionAccess().getEntityActionAssignment_0(), "rule__ImperativeEntityAction__EntityActionAssignment_0");
			builder.put(grammarAccess.getImperativeEntityActionAccess().getAdverbAssignment_1(), "rule__ImperativeEntityAction__AdverbAssignment_1");
			builder.put(grammarAccess.getImperativeEntityActionAccess().getActionDefAssignment_2(), "rule__ImperativeEntityAction__ActionDefAssignment_2");
			builder.put(grammarAccess.getImperativeEntityActionAccess().getPropertyRefAssignment_3(), "rule__ImperativeEntityAction__PropertyRefAssignment_3");
			builder.put(grammarAccess.getPropertyRefAccess().getPropertyrefAssignment_0(), "rule__PropertyRef__PropertyrefAssignment_0");
			builder.put(grammarAccess.getPropertyRefAccess().getPropertyAssignment_1(), "rule__PropertyRef__PropertyAssignment_1");
			builder.put(grammarAccess.getPropertyRefAccess().getPropertyValueAssignment_2(), "rule__PropertyRef__PropertyValueAssignment_2");
			builder.put(grammarAccess.getPropertyRefAccess().getProperyValue2Assignment_3_1(), "rule__PropertyRef__ProperyValue2Assignment_3_1");
			builder.put(grammarAccess.getPropertyRefAccess().getPropery2Assignment_3_2(), "rule__PropertyRef__Propery2Assignment_3_2");
			builder.put(grammarAccess.getImperativePropertyRefAccess().getPropertyrefAssignment_0(), "rule__ImperativePropertyRef__PropertyrefAssignment_0");
			builder.put(grammarAccess.getImperativePropertyRefAccess().getPropertyAssignment_1(), "rule__ImperativePropertyRef__PropertyAssignment_1");
			builder.put(grammarAccess.getImperativePropertyRefAccess().getPropertyValueAssignment_2(), "rule__ImperativePropertyRef__PropertyValueAssignment_2");
			builder.put(grammarAccess.getImperativePropertyRefAccess().getProperyValue2Assignment_3_1(), "rule__ImperativePropertyRef__ProperyValue2Assignment_3_1");
			builder.put(grammarAccess.getImperativePropertyRefAccess().getPropery2Assignment_3_2(), "rule__ImperativePropertyRef__Propery2Assignment_3_2");
			builder.put(grammarAccess.getDeclarativeActionRefAccess().getVerbAssignment_0(), "rule__DeclarativeActionRef__VerbAssignment_0");
			builder.put(grammarAccess.getDeclarativeActionRefAccess().getArgumentAssignment_2(), "rule__DeclarativeActionRef__ArgumentAssignment_2");
			builder.put(grammarAccess.getDeclarativeActionRefAccess().getPrepositionAssignment_3(), "rule__DeclarativeActionRef__PrepositionAssignment_3");
			builder.put(grammarAccess.getDeclarativeActionRefAccess().getEntityAssignment_4_1(), "rule__DeclarativeActionRef__EntityAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BddDslGrammarAccess grammarAccess;

	@Override
	protected InternalBddDslParser createParser() {
		InternalBddDslParser result = new InternalBddDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BddDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BddDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
