/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage
 * @generated
 */
public interface BddDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BddDslFactory eINSTANCE = dk.sdu.bdd.xtext.bddDsl.impl.BddDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Model Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Ref</em>'.
   * @generated
   */
  ModelRef createModelRef();

  /**
   * Returns a new object of class '<em>Declarative Entity Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative Entity Def</em>'.
   * @generated
   */
  DeclarativeEntityDef createDeclarativeEntityDef();

  /**
   * Returns a new object of class '<em>Imperative Entity Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Entity Def</em>'.
   * @generated
   */
  ImperativeEntityDef createImperativeEntityDef();

  /**
   * Returns a new object of class '<em>Imperative Action Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Action Def</em>'.
   * @generated
   */
  ImperativeActionDef createImperativeActionDef();

  /**
   * Returns a new object of class '<em>Action Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Def</em>'.
   * @generated
   */
  ActionDef createActionDef();

  /**
   * Returns a new object of class '<em>State Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Def</em>'.
   * @generated
   */
  StateDef createStateDef();

  /**
   * Returns a new object of class '<em>State Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Name</em>'.
   * @generated
   */
  StateName createStateName();

  /**
   * Returns a new object of class '<em>Property Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property Def</em>'.
   * @generated
   */
  PropertyDef createPropertyDef();

  /**
   * Returns a new object of class '<em>Imperative State Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative State Def</em>'.
   * @generated
   */
  ImperativeStateDef createImperativeStateDef();

  /**
   * Returns a new object of class '<em>Imperative State Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative State Name</em>'.
   * @generated
   */
  ImperativeStateName createImperativeStateName();

  /**
   * Returns a new object of class '<em>Imperative Property Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Property Def</em>'.
   * @generated
   */
  ImperativePropertyDef createImperativePropertyDef();

  /**
   * Returns a new object of class '<em>Imperative Scenario</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Scenario</em>'.
   * @generated
   */
  ImperativeScenario createImperativeScenario();

  /**
   * Returns a new object of class '<em>Scenario</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scenario</em>'.
   * @generated
   */
  Scenario createScenario();

  /**
   * Returns a new object of class '<em>Declarative Scenario State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative Scenario State</em>'.
   * @generated
   */
  DeclarativeScenarioState createDeclarativeScenarioState();

  /**
   * Returns a new object of class '<em>Imperative Scenario State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Scenario State</em>'.
   * @generated
   */
  ImperativeScenarioState createImperativeScenarioState();

  /**
   * Returns a new object of class '<em>Declarative Scenario Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative Scenario Action</em>'.
   * @generated
   */
  DeclarativeScenarioAction createDeclarativeScenarioAction();

  /**
   * Returns a new object of class '<em>Imperative Scenario Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Scenario Action</em>'.
   * @generated
   */
  ImperativeScenarioAction createImperativeScenarioAction();

  /**
   * Returns a new object of class '<em>Declarative State Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative State Phrase</em>'.
   * @generated
   */
  DeclarativeStatePhrase createDeclarativeStatePhrase();

  /**
   * Returns a new object of class '<em>Imperative State Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative State Phrase</em>'.
   * @generated
   */
  ImperativeStatePhrase createImperativeStatePhrase();

  /**
   * Returns a new object of class '<em>Declarative Entity Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative Entity Ref</em>'.
   * @generated
   */
  DeclarativeEntityRef createDeclarativeEntityRef();

  /**
   * Returns a new object of class '<em>Imperative Entity Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Entity Ref</em>'.
   * @generated
   */
  ImperativeEntityRef createImperativeEntityRef();

  /**
   * Returns a new object of class '<em>Declarative Entity State Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative Entity State Phrase</em>'.
   * @generated
   */
  DeclarativeEntityStatePhrase createDeclarativeEntityStatePhrase();

  /**
   * Returns a new object of class '<em>Imperative Entity State Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Entity State Phrase</em>'.
   * @generated
   */
  ImperativeEntityStatePhrase createImperativeEntityStatePhrase();

  /**
   * Returns a new object of class '<em>Declarative Entity Property State Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative Entity Property State Phrase</em>'.
   * @generated
   */
  DeclarativeEntityPropertyStatePhrase createDeclarativeEntityPropertyStatePhrase();

  /**
   * Returns a new object of class '<em>Imperative Entity Property State Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Entity Property State Phrase</em>'.
   * @generated
   */
  ImperativeEntityPropertyStatePhrase createImperativeEntityPropertyStatePhrase();

  /**
   * Returns a new object of class '<em>Simple Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Value</em>'.
   * @generated
   */
  SimpleValue createSimpleValue();

  /**
   * Returns a new object of class '<em>String Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Value</em>'.
   * @generated
   */
  StringValue createStringValue();

  /**
   * Returns a new object of class '<em>Int Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Value</em>'.
   * @generated
   */
  IntValue createIntValue();

  /**
   * Returns a new object of class '<em>Double Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Double Value</em>'.
   * @generated
   */
  DoubleValue createDoubleValue();

  /**
   * Returns a new object of class '<em>Declarative Action Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative Action Phrase</em>'.
   * @generated
   */
  DeclarativeActionPhrase createDeclarativeActionPhrase();

  /**
   * Returns a new object of class '<em>Imperative Action Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Action Phrase</em>'.
   * @generated
   */
  ImperativeActionPhrase createImperativeActionPhrase();

  /**
   * Returns a new object of class '<em>Verb Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Verb Action</em>'.
   * @generated
   */
  VerbAction createVerbAction();

  /**
   * Returns a new object of class '<em>Declarative Entity Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative Entity Action</em>'.
   * @generated
   */
  DeclarativeEntityAction createDeclarativeEntityAction();

  /**
   * Returns a new object of class '<em>Imperative Entity Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Entity Action</em>'.
   * @generated
   */
  ImperativeEntityAction createImperativeEntityAction();

  /**
   * Returns a new object of class '<em>Property Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property Ref</em>'.
   * @generated
   */
  PropertyRef createPropertyRef();

  /**
   * Returns a new object of class '<em>Imperative Property Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imperative Property Ref</em>'.
   * @generated
   */
  ImperativePropertyRef createImperativePropertyRef();

  /**
   * Returns a new object of class '<em>Declarative Action Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarative Action Ref</em>'.
   * @generated
   */
  DeclarativeActionRef createDeclarativeActionRef();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BddDslPackage getBddDslPackage();

} //BddDslFactory
