/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarative Action Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeActionPhrase()
 * @model
 * @generated
 */
public interface DeclarativeActionPhrase extends EObject
{
} // DeclarativeActionPhrase
