/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarative Entity Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getEntityAction <em>Entity Action</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getActionDef <em>Action Def</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getEntityRef <em>Entity Ref</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getPropertyRef <em>Property Ref</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction()
 * @model
 * @generated
 */
public interface DeclarativeEntityAction extends DeclarativeActionPhrase
{
  /**
   * Returns the value of the '<em><b>Entity Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Action</em>' containment reference.
   * @see #setEntityAction(DeclarativeEntityRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction_EntityAction()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityRef getEntityAction();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getEntityAction <em>Entity Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Action</em>' containment reference.
   * @see #getEntityAction()
   * @generated
   */
  void setEntityAction(DeclarativeEntityRef value);

  /**
   * Returns the value of the '<em><b>Action Def</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Def</em>' reference.
   * @see #setActionDef(ActionDef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction_ActionDef()
   * @model
   * @generated
   */
  ActionDef getActionDef();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getActionDef <em>Action Def</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Def</em>' reference.
   * @see #getActionDef()
   * @generated
   */
  void setActionDef(ActionDef value);

  /**
   * Returns the value of the '<em><b>Entity Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Ref</em>' containment reference.
   * @see #setEntityRef(DeclarativeEntityRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction_EntityRef()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityRef getEntityRef();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getEntityRef <em>Entity Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Ref</em>' containment reference.
   * @see #getEntityRef()
   * @generated
   */
  void setEntityRef(DeclarativeEntityRef value);

  /**
   * Returns the value of the '<em><b>Property Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Ref</em>' containment reference.
   * @see #setPropertyRef(PropertyRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction_PropertyRef()
   * @model containment="true"
   * @generated
   */
  PropertyRef getPropertyRef();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getPropertyRef <em>Property Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Ref</em>' containment reference.
   * @see #getPropertyRef()
   * @generated
   */
  void setPropertyRef(PropertyRef value);

} // DeclarativeEntityAction
