/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarative State Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeStatePhrase#getEsp <em>Esp</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeStatePhrase()
 * @model
 * @generated
 */
public interface DeclarativeStatePhrase extends EObject
{
  /**
   * Returns the value of the '<em><b>Esp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Esp</em>' containment reference.
   * @see #setEsp(DeclarativeEntityStatePhrase)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeStatePhrase_Esp()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityStatePhrase getEsp();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeStatePhrase#getEsp <em>Esp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Esp</em>' containment reference.
   * @see #getEsp()
   * @generated
   */
  void setEsp(DeclarativeEntityStatePhrase value);

} // DeclarativeStatePhrase
