/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarative Action Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeActionRef#getVerb <em>Verb</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeActionRef#getArgument <em>Argument</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeActionRef#getPreposition <em>Preposition</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeActionRef#getEntity <em>Entity</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeActionRef()
 * @model
 * @generated
 */
public interface DeclarativeActionRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Verb</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verb</em>' reference.
   * @see #setVerb(ActionDef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeActionRef_Verb()
   * @model
   * @generated
   */
  ActionDef getVerb();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeActionRef#getVerb <em>Verb</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verb</em>' reference.
   * @see #getVerb()
   * @generated
   */
  void setVerb(ActionDef value);

  /**
   * Returns the value of the '<em><b>Argument</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument</em>' containment reference.
   * @see #setArgument(SimpleValue)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeActionRef_Argument()
   * @model containment="true"
   * @generated
   */
  SimpleValue getArgument();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeActionRef#getArgument <em>Argument</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument</em>' containment reference.
   * @see #getArgument()
   * @generated
   */
  void setArgument(SimpleValue value);

  /**
   * Returns the value of the '<em><b>Preposition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preposition</em>' attribute.
   * @see #setPreposition(String)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeActionRef_Preposition()
   * @model
   * @generated
   */
  String getPreposition();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeActionRef#getPreposition <em>Preposition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preposition</em>' attribute.
   * @see #getPreposition()
   * @generated
   */
  void setPreposition(String value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' containment reference.
   * @see #setEntity(DeclarativeEntityDef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeActionRef_Entity()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityDef getEntity();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeActionRef#getEntity <em>Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' containment reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(DeclarativeEntityDef value);

} // DeclarativeActionRef
