/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Imperative Entity Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativeEntityAction#getEntityAction <em>Entity Action</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativeEntityAction#getAdverb <em>Adverb</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativeEntityAction#getActionDef <em>Action Def</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativeEntityAction#getPropertyRef <em>Property Ref</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeEntityAction()
 * @model
 * @generated
 */
public interface ImperativeEntityAction extends ImperativeActionPhrase
{
  /**
   * Returns the value of the '<em><b>Entity Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Action</em>' containment reference.
   * @see #setEntityAction(ImperativeEntityRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeEntityAction_EntityAction()
   * @model containment="true"
   * @generated
   */
  ImperativeEntityRef getEntityAction();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativeEntityAction#getEntityAction <em>Entity Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Action</em>' containment reference.
   * @see #getEntityAction()
   * @generated
   */
  void setEntityAction(ImperativeEntityRef value);

  /**
   * Returns the value of the '<em><b>Adverb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Adverb</em>' attribute.
   * @see #setAdverb(String)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeEntityAction_Adverb()
   * @model
   * @generated
   */
  String getAdverb();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativeEntityAction#getAdverb <em>Adverb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Adverb</em>' attribute.
   * @see #getAdverb()
   * @generated
   */
  void setAdverb(String value);

  /**
   * Returns the value of the '<em><b>Action Def</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Def</em>' reference.
   * @see #setActionDef(ImperativeActionDef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeEntityAction_ActionDef()
   * @model
   * @generated
   */
  ImperativeActionDef getActionDef();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativeEntityAction#getActionDef <em>Action Def</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Def</em>' reference.
   * @see #getActionDef()
   * @generated
   */
  void setActionDef(ImperativeActionDef value);

  /**
   * Returns the value of the '<em><b>Property Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Ref</em>' containment reference.
   * @see #setPropertyRef(ImperativePropertyRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeEntityAction_PropertyRef()
   * @model containment="true"
   * @generated
   */
  ImperativePropertyRef getPropertyRef();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativeEntityAction#getPropertyRef <em>Property Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Ref</em>' containment reference.
   * @see #getPropertyRef()
   * @generated
   */
  void setPropertyRef(ImperativePropertyRef value);

} // ImperativeEntityAction
