/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Imperative Property Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getPropertyref <em>Propertyref</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getProperty <em>Property</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getPropertyValue <em>Property Value</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getProperyValue2 <em>Propery Value2</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getPropery2 <em>Propery2</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativePropertyRef()
 * @model
 * @generated
 */
public interface ImperativePropertyRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Propertyref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Propertyref</em>' attribute.
   * @see #setPropertyref(String)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativePropertyRef_Propertyref()
   * @model
   * @generated
   */
  String getPropertyref();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getPropertyref <em>Propertyref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Propertyref</em>' attribute.
   * @see #getPropertyref()
   * @generated
   */
  void setPropertyref(String value);

  /**
   * Returns the value of the '<em><b>Property</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' reference.
   * @see #setProperty(ImperativePropertyDef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativePropertyRef_Property()
   * @model
   * @generated
   */
  ImperativePropertyDef getProperty();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getProperty <em>Property</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' reference.
   * @see #getProperty()
   * @generated
   */
  void setProperty(ImperativePropertyDef value);

  /**
   * Returns the value of the '<em><b>Property Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Value</em>' containment reference.
   * @see #setPropertyValue(StringValue)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativePropertyRef_PropertyValue()
   * @model containment="true"
   * @generated
   */
  StringValue getPropertyValue();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getPropertyValue <em>Property Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Value</em>' containment reference.
   * @see #getPropertyValue()
   * @generated
   */
  void setPropertyValue(StringValue value);

  /**
   * Returns the value of the '<em><b>Propery Value2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Propery Value2</em>' containment reference.
   * @see #setProperyValue2(StringValue)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativePropertyRef_ProperyValue2()
   * @model containment="true"
   * @generated
   */
  StringValue getProperyValue2();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getProperyValue2 <em>Propery Value2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Propery Value2</em>' containment reference.
   * @see #getProperyValue2()
   * @generated
   */
  void setProperyValue2(StringValue value);

  /**
   * Returns the value of the '<em><b>Propery2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Propery2</em>' reference.
   * @see #setPropery2(ImperativePropertyDef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativePropertyRef_Propery2()
   * @model
   * @generated
   */
  ImperativePropertyDef getPropery2();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef#getPropery2 <em>Propery2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Propery2</em>' reference.
   * @see #getPropery2()
   * @generated
   */
  void setPropery2(ImperativePropertyDef value);

} // ImperativePropertyRef
