/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Imperative State Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativeStateName#getImpStatName <em>Imp Stat Name</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeStateName()
 * @model
 * @generated
 */
public interface ImperativeStateName extends EObject
{
  /**
   * Returns the value of the '<em><b>Imp Stat Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imp Stat Name</em>' containment reference.
   * @see #setImpStatName(StateName)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeStateName_ImpStatName()
   * @model containment="true"
   * @generated
   */
  StateName getImpStatName();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativeStateName#getImpStatName <em>Imp Stat Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imp Stat Name</em>' containment reference.
   * @see #getImpStatName()
   * @generated
   */
  void setImpStatName(StateName value);

} // ImperativeStateName
