/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getSimpleValue()
 * @model
 * @generated
 */
public interface SimpleValue extends EObject
{
} // SimpleValue
