/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verb Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getAction <em>Action</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity <em>Entity</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity2 <em>Entity2</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity3 <em>Entity3</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction()
 * @model
 * @generated
 */
public interface VerbAction extends DeclarativeActionPhrase
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(DeclarativeActionRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Action()
   * @model containment="true"
   * @generated
   */
  DeclarativeActionRef getAction();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(DeclarativeActionRef value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' containment reference.
   * @see #setEntity(DeclarativeEntityDef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Entity()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityDef getEntity();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity <em>Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' containment reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(DeclarativeEntityDef value);

  /**
   * Returns the value of the '<em><b>Entity2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity2</em>' containment reference.
   * @see #setEntity2(DeclarativeEntityRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Entity2()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityRef getEntity2();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity2 <em>Entity2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity2</em>' containment reference.
   * @see #getEntity2()
   * @generated
   */
  void setEntity2(DeclarativeEntityRef value);

  /**
   * Returns the value of the '<em><b>Entity3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity3</em>' containment reference.
   * @see #setEntity3(DeclarativeEntityRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Entity3()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityRef getEntity3();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity3 <em>Entity3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity3</em>' containment reference.
   * @see #getEntity3()
   * @generated
   */
  void setEntity3(DeclarativeEntityRef value);

} // VerbAction
