/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl.impl;

import dk.sdu.bdd.xtext.bddDsl.ActionDef;
import dk.sdu.bdd.xtext.bddDsl.BddDslFactory;
import dk.sdu.bdd.xtext.bddDsl.BddDslPackage;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeActionPhrase;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeActionRef;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityDef;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityPropertyStatePhrase;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityRef;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityStatePhrase;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeScenarioAction;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeScenarioState;
import dk.sdu.bdd.xtext.bddDsl.DeclarativeStatePhrase;
import dk.sdu.bdd.xtext.bddDsl.DoubleValue;
import dk.sdu.bdd.xtext.bddDsl.ImperativeActionDef;
import dk.sdu.bdd.xtext.bddDsl.ImperativeActionPhrase;
import dk.sdu.bdd.xtext.bddDsl.ImperativeEntityAction;
import dk.sdu.bdd.xtext.bddDsl.ImperativeEntityDef;
import dk.sdu.bdd.xtext.bddDsl.ImperativeEntityPropertyStatePhrase;
import dk.sdu.bdd.xtext.bddDsl.ImperativeEntityRef;
import dk.sdu.bdd.xtext.bddDsl.ImperativeEntityStatePhrase;
import dk.sdu.bdd.xtext.bddDsl.ImperativePropertyDef;
import dk.sdu.bdd.xtext.bddDsl.ImperativePropertyRef;
import dk.sdu.bdd.xtext.bddDsl.ImperativeScenario;
import dk.sdu.bdd.xtext.bddDsl.ImperativeScenarioAction;
import dk.sdu.bdd.xtext.bddDsl.ImperativeScenarioState;
import dk.sdu.bdd.xtext.bddDsl.ImperativeStateDef;
import dk.sdu.bdd.xtext.bddDsl.ImperativeStateName;
import dk.sdu.bdd.xtext.bddDsl.ImperativeStatePhrase;
import dk.sdu.bdd.xtext.bddDsl.IntValue;
import dk.sdu.bdd.xtext.bddDsl.Model;
import dk.sdu.bdd.xtext.bddDsl.ModelRef;
import dk.sdu.bdd.xtext.bddDsl.PropertyDef;
import dk.sdu.bdd.xtext.bddDsl.PropertyRef;
import dk.sdu.bdd.xtext.bddDsl.Scenario;
import dk.sdu.bdd.xtext.bddDsl.SimpleValue;
import dk.sdu.bdd.xtext.bddDsl.StateDef;
import dk.sdu.bdd.xtext.bddDsl.StateName;
import dk.sdu.bdd.xtext.bddDsl.StringValue;
import dk.sdu.bdd.xtext.bddDsl.VerbAction;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BddDslPackageImpl extends EPackageImpl implements BddDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeEntityDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeEntityDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeActionDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stateDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stateNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass propertyDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeStateDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeStateNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativePropertyDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeScenarioEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass scenarioEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeScenarioStateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeScenarioStateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeScenarioActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeScenarioActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeStatePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeStatePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeEntityRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeEntityRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeEntityStatePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeEntityStatePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeEntityPropertyStatePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeEntityPropertyStatePhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simpleValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass intValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass doubleValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeActionPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeActionPhraseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass verbActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeEntityActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativeEntityActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass propertyRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imperativePropertyRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declarativeActionRefEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private BddDslPackageImpl()
  {
    super(eNS_URI, BddDslFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link BddDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static BddDslPackage init()
  {
    if (isInited) return (BddDslPackage)EPackage.Registry.INSTANCE.getEPackage(BddDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredBddDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    BddDslPackageImpl theBddDslPackage = registeredBddDslPackage instanceof BddDslPackageImpl ? (BddDslPackageImpl)registeredBddDslPackage : new BddDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theBddDslPackage.createPackageContents();

    // Initialize created meta-data
    theBddDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theBddDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(BddDslPackage.eNS_URI, theBddDslPackage);
    return theBddDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getModel_Name()
  {
    return (EAttribute)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_ModelRefs()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_DeclarativeEntityDef()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_ImperativeEntityDef()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Scenarios()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelRef()
  {
    return modelRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelRef_ModelRef()
  {
    return (EReference)modelRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeEntityDef()
  {
    return declarativeEntityDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeclarativeEntityDef_Name()
  {
    return (EAttribute)declarativeEntityDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityDef_SuperEntities()
  {
    return (EReference)declarativeEntityDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityDef_Actions()
  {
    return (EReference)declarativeEntityDefEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityDef_States()
  {
    return (EReference)declarativeEntityDefEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityDef_Properties()
  {
    return (EReference)declarativeEntityDefEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeEntityDef()
  {
    return imperativeEntityDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImperativeEntityDef_Name()
  {
    return (EAttribute)imperativeEntityDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityDef_SuperEntities()
  {
    return (EReference)imperativeEntityDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityDef_Actions()
  {
    return (EReference)imperativeEntityDefEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityDef_States()
  {
    return (EReference)imperativeEntityDefEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityDef_Properties()
  {
    return (EReference)imperativeEntityDefEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeActionDef()
  {
    return imperativeActionDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImperativeActionDef_Name()
  {
    return (EAttribute)imperativeActionDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getActionDef()
  {
    return actionDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getActionDef_Name()
  {
    return (EAttribute)actionDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStateDef()
  {
    return stateDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStateDef_Postive()
  {
    return (EReference)stateDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStateDef_Negative()
  {
    return (EReference)stateDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStateName()
  {
    return stateNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStateName_Name()
  {
    return (EAttribute)stateNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStateName_Name2()
  {
    return (EAttribute)stateNameEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStateName_Name3()
  {
    return (EAttribute)stateNameEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPropertyDef()
  {
    return propertyDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropertyDef_Name()
  {
    return (EAttribute)propertyDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropertyDef_Plural()
  {
    return (EAttribute)propertyDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeStateDef()
  {
    return imperativeStateDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeStateDef_Postive()
  {
    return (EReference)imperativeStateDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeStateDef_Negative()
  {
    return (EReference)imperativeStateDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeStateName()
  {
    return imperativeStateNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeStateName_ImpStatName()
  {
    return (EReference)imperativeStateNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativePropertyDef()
  {
    return imperativePropertyDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImperativePropertyDef_Name()
  {
    return (EAttribute)imperativePropertyDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImperativePropertyDef_Plural()
  {
    return (EAttribute)imperativePropertyDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeScenario()
  {
    return imperativeScenarioEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeScenario_PreState()
  {
    return (EReference)imperativeScenarioEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeScenario_Action()
  {
    return (EReference)imperativeScenarioEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeScenario_PostState()
  {
    return (EReference)imperativeScenarioEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getScenario()
  {
    return scenarioEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getScenario_Name()
  {
    return (EAttribute)scenarioEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScenario_PreStateE()
  {
    return (EReference)scenarioEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScenario_Imperative1()
  {
    return (EReference)scenarioEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScenario_ActionE()
  {
    return (EReference)scenarioEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScenario_Imperative2()
  {
    return (EReference)scenarioEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScenario_PreStateE1()
  {
    return (EReference)scenarioEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScenario_Imperative3()
  {
    return (EReference)scenarioEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeScenarioState()
  {
    return declarativeScenarioStateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeScenarioState_States()
  {
    return (EReference)declarativeScenarioStateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeScenarioState()
  {
    return imperativeScenarioStateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeScenarioState_States()
  {
    return (EReference)imperativeScenarioStateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeScenarioAction()
  {
    return declarativeScenarioActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeScenarioAction_Actions()
  {
    return (EReference)declarativeScenarioActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeScenarioAction()
  {
    return imperativeScenarioActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeScenarioAction_Actions()
  {
    return (EReference)imperativeScenarioActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeStatePhrase()
  {
    return declarativeStatePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeStatePhrase_Esp()
  {
    return (EReference)declarativeStatePhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeStatePhrase()
  {
    return imperativeStatePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeStatePhrase_Epsp()
  {
    return (EReference)imperativeStatePhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeStatePhrase_Esp()
  {
    return (EReference)imperativeStatePhraseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeEntityRef()
  {
    return declarativeEntityRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityRef_Entity()
  {
    return (EReference)declarativeEntityRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeclarativeEntityRef_Name()
  {
    return (EAttribute)declarativeEntityRefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeEntityRef()
  {
    return imperativeEntityRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityRef_Entity()
  {
    return (EReference)imperativeEntityRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImperativeEntityRef_Name()
  {
    return (EAttribute)imperativeEntityRefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeEntityStatePhrase()
  {
    return declarativeEntityStatePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityStatePhrase_Property()
  {
    return (EReference)declarativeEntityStatePhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityStatePhrase_Entity()
  {
    return (EReference)declarativeEntityStatePhraseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityStatePhrase_State()
  {
    return (EReference)declarativeEntityStatePhraseEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeEntityStatePhrase()
  {
    return imperativeEntityStatePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityStatePhrase_Entity()
  {
    return (EReference)imperativeEntityStatePhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityStatePhrase_State()
  {
    return (EReference)imperativeEntityStatePhraseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeEntityPropertyStatePhrase()
  {
    return declarativeEntityPropertyStatePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityPropertyStatePhrase_Property()
  {
    return (EReference)declarativeEntityPropertyStatePhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityPropertyStatePhrase_Entity()
  {
    return (EReference)declarativeEntityPropertyStatePhraseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityPropertyStatePhrase_Value()
  {
    return (EReference)declarativeEntityPropertyStatePhraseEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityPropertyStatePhrase_Values()
  {
    return (EReference)declarativeEntityPropertyStatePhraseEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeEntityPropertyStatePhrase()
  {
    return imperativeEntityPropertyStatePhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityPropertyStatePhrase_Property()
  {
    return (EReference)imperativeEntityPropertyStatePhraseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityPropertyStatePhrase_Entity()
  {
    return (EReference)imperativeEntityPropertyStatePhraseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityPropertyStatePhrase_PropertyValue()
  {
    return (EReference)imperativeEntityPropertyStatePhraseEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSimpleValue()
  {
    return simpleValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStringValue()
  {
    return stringValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStringValue_Value()
  {
    return (EAttribute)stringValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntValue()
  {
    return intValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntValue_Value()
  {
    return (EAttribute)intValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDoubleValue()
  {
    return doubleValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDoubleValue_Value()
  {
    return (EAttribute)doubleValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeActionPhrase()
  {
    return declarativeActionPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeActionPhrase()
  {
    return imperativeActionPhraseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVerbAction()
  {
    return verbActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVerbAction_Action()
  {
    return (EReference)verbActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVerbAction_Entity()
  {
    return (EReference)verbActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVerbAction_Entity2()
  {
    return (EReference)verbActionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVerbAction_Entity3()
  {
    return (EReference)verbActionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeEntityAction()
  {
    return declarativeEntityActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityAction_EntityAction()
  {
    return (EReference)declarativeEntityActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityAction_ActionDef()
  {
    return (EReference)declarativeEntityActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityAction_EntityRef()
  {
    return (EReference)declarativeEntityActionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeEntityAction_PropertyRef()
  {
    return (EReference)declarativeEntityActionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativeEntityAction()
  {
    return imperativeEntityActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityAction_EntityAction()
  {
    return (EReference)imperativeEntityActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImperativeEntityAction_Adverb()
  {
    return (EAttribute)imperativeEntityActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityAction_ActionDef()
  {
    return (EReference)imperativeEntityActionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativeEntityAction_PropertyRef()
  {
    return (EReference)imperativeEntityActionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPropertyRef()
  {
    return propertyRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropertyRef_Propertyref()
  {
    return (EAttribute)propertyRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPropertyRef_Property()
  {
    return (EReference)propertyRefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPropertyRef_PropertyValue()
  {
    return (EReference)propertyRefEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPropertyRef_ProperyValue2()
  {
    return (EReference)propertyRefEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPropertyRef_Propery2()
  {
    return (EReference)propertyRefEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImperativePropertyRef()
  {
    return imperativePropertyRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImperativePropertyRef_Propertyref()
  {
    return (EAttribute)imperativePropertyRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativePropertyRef_Property()
  {
    return (EReference)imperativePropertyRefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativePropertyRef_PropertyValue()
  {
    return (EReference)imperativePropertyRefEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativePropertyRef_ProperyValue2()
  {
    return (EReference)imperativePropertyRefEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImperativePropertyRef_Propery2()
  {
    return (EReference)imperativePropertyRefEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclarativeActionRef()
  {
    return declarativeActionRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeActionRef_Verb()
  {
    return (EReference)declarativeActionRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeActionRef_Argument()
  {
    return (EReference)declarativeActionRefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeclarativeActionRef_Preposition()
  {
    return (EAttribute)declarativeActionRefEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclarativeActionRef_Entity()
  {
    return (EReference)declarativeActionRefEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BddDslFactory getBddDslFactory()
  {
    return (BddDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEAttribute(modelEClass, MODEL__NAME);
    createEReference(modelEClass, MODEL__MODEL_REFS);
    createEReference(modelEClass, MODEL__DECLARATIVE_ENTITY_DEF);
    createEReference(modelEClass, MODEL__IMPERATIVE_ENTITY_DEF);
    createEReference(modelEClass, MODEL__SCENARIOS);

    modelRefEClass = createEClass(MODEL_REF);
    createEReference(modelRefEClass, MODEL_REF__MODEL_REF);

    declarativeEntityDefEClass = createEClass(DECLARATIVE_ENTITY_DEF);
    createEAttribute(declarativeEntityDefEClass, DECLARATIVE_ENTITY_DEF__NAME);
    createEReference(declarativeEntityDefEClass, DECLARATIVE_ENTITY_DEF__SUPER_ENTITIES);
    createEReference(declarativeEntityDefEClass, DECLARATIVE_ENTITY_DEF__ACTIONS);
    createEReference(declarativeEntityDefEClass, DECLARATIVE_ENTITY_DEF__STATES);
    createEReference(declarativeEntityDefEClass, DECLARATIVE_ENTITY_DEF__PROPERTIES);

    imperativeEntityDefEClass = createEClass(IMPERATIVE_ENTITY_DEF);
    createEAttribute(imperativeEntityDefEClass, IMPERATIVE_ENTITY_DEF__NAME);
    createEReference(imperativeEntityDefEClass, IMPERATIVE_ENTITY_DEF__SUPER_ENTITIES);
    createEReference(imperativeEntityDefEClass, IMPERATIVE_ENTITY_DEF__ACTIONS);
    createEReference(imperativeEntityDefEClass, IMPERATIVE_ENTITY_DEF__STATES);
    createEReference(imperativeEntityDefEClass, IMPERATIVE_ENTITY_DEF__PROPERTIES);

    imperativeActionDefEClass = createEClass(IMPERATIVE_ACTION_DEF);
    createEAttribute(imperativeActionDefEClass, IMPERATIVE_ACTION_DEF__NAME);

    actionDefEClass = createEClass(ACTION_DEF);
    createEAttribute(actionDefEClass, ACTION_DEF__NAME);

    stateDefEClass = createEClass(STATE_DEF);
    createEReference(stateDefEClass, STATE_DEF__POSTIVE);
    createEReference(stateDefEClass, STATE_DEF__NEGATIVE);

    stateNameEClass = createEClass(STATE_NAME);
    createEAttribute(stateNameEClass, STATE_NAME__NAME);
    createEAttribute(stateNameEClass, STATE_NAME__NAME2);
    createEAttribute(stateNameEClass, STATE_NAME__NAME3);

    propertyDefEClass = createEClass(PROPERTY_DEF);
    createEAttribute(propertyDefEClass, PROPERTY_DEF__NAME);
    createEAttribute(propertyDefEClass, PROPERTY_DEF__PLURAL);

    imperativeStateDefEClass = createEClass(IMPERATIVE_STATE_DEF);
    createEReference(imperativeStateDefEClass, IMPERATIVE_STATE_DEF__POSTIVE);
    createEReference(imperativeStateDefEClass, IMPERATIVE_STATE_DEF__NEGATIVE);

    imperativeStateNameEClass = createEClass(IMPERATIVE_STATE_NAME);
    createEReference(imperativeStateNameEClass, IMPERATIVE_STATE_NAME__IMP_STAT_NAME);

    imperativePropertyDefEClass = createEClass(IMPERATIVE_PROPERTY_DEF);
    createEAttribute(imperativePropertyDefEClass, IMPERATIVE_PROPERTY_DEF__NAME);
    createEAttribute(imperativePropertyDefEClass, IMPERATIVE_PROPERTY_DEF__PLURAL);

    imperativeScenarioEClass = createEClass(IMPERATIVE_SCENARIO);
    createEReference(imperativeScenarioEClass, IMPERATIVE_SCENARIO__PRE_STATE);
    createEReference(imperativeScenarioEClass, IMPERATIVE_SCENARIO__ACTION);
    createEReference(imperativeScenarioEClass, IMPERATIVE_SCENARIO__POST_STATE);

    scenarioEClass = createEClass(SCENARIO);
    createEAttribute(scenarioEClass, SCENARIO__NAME);
    createEReference(scenarioEClass, SCENARIO__PRE_STATE_E);
    createEReference(scenarioEClass, SCENARIO__IMPERATIVE1);
    createEReference(scenarioEClass, SCENARIO__ACTION_E);
    createEReference(scenarioEClass, SCENARIO__IMPERATIVE2);
    createEReference(scenarioEClass, SCENARIO__PRE_STATE_E1);
    createEReference(scenarioEClass, SCENARIO__IMPERATIVE3);

    declarativeScenarioStateEClass = createEClass(DECLARATIVE_SCENARIO_STATE);
    createEReference(declarativeScenarioStateEClass, DECLARATIVE_SCENARIO_STATE__STATES);

    imperativeScenarioStateEClass = createEClass(IMPERATIVE_SCENARIO_STATE);
    createEReference(imperativeScenarioStateEClass, IMPERATIVE_SCENARIO_STATE__STATES);

    declarativeScenarioActionEClass = createEClass(DECLARATIVE_SCENARIO_ACTION);
    createEReference(declarativeScenarioActionEClass, DECLARATIVE_SCENARIO_ACTION__ACTIONS);

    imperativeScenarioActionEClass = createEClass(IMPERATIVE_SCENARIO_ACTION);
    createEReference(imperativeScenarioActionEClass, IMPERATIVE_SCENARIO_ACTION__ACTIONS);

    declarativeStatePhraseEClass = createEClass(DECLARATIVE_STATE_PHRASE);
    createEReference(declarativeStatePhraseEClass, DECLARATIVE_STATE_PHRASE__ESP);

    imperativeStatePhraseEClass = createEClass(IMPERATIVE_STATE_PHRASE);
    createEReference(imperativeStatePhraseEClass, IMPERATIVE_STATE_PHRASE__EPSP);
    createEReference(imperativeStatePhraseEClass, IMPERATIVE_STATE_PHRASE__ESP);

    declarativeEntityRefEClass = createEClass(DECLARATIVE_ENTITY_REF);
    createEReference(declarativeEntityRefEClass, DECLARATIVE_ENTITY_REF__ENTITY);
    createEAttribute(declarativeEntityRefEClass, DECLARATIVE_ENTITY_REF__NAME);

    imperativeEntityRefEClass = createEClass(IMPERATIVE_ENTITY_REF);
    createEReference(imperativeEntityRefEClass, IMPERATIVE_ENTITY_REF__ENTITY);
    createEAttribute(imperativeEntityRefEClass, IMPERATIVE_ENTITY_REF__NAME);

    declarativeEntityStatePhraseEClass = createEClass(DECLARATIVE_ENTITY_STATE_PHRASE);
    createEReference(declarativeEntityStatePhraseEClass, DECLARATIVE_ENTITY_STATE_PHRASE__PROPERTY);
    createEReference(declarativeEntityStatePhraseEClass, DECLARATIVE_ENTITY_STATE_PHRASE__ENTITY);
    createEReference(declarativeEntityStatePhraseEClass, DECLARATIVE_ENTITY_STATE_PHRASE__STATE);

    imperativeEntityStatePhraseEClass = createEClass(IMPERATIVE_ENTITY_STATE_PHRASE);
    createEReference(imperativeEntityStatePhraseEClass, IMPERATIVE_ENTITY_STATE_PHRASE__ENTITY);
    createEReference(imperativeEntityStatePhraseEClass, IMPERATIVE_ENTITY_STATE_PHRASE__STATE);

    declarativeEntityPropertyStatePhraseEClass = createEClass(DECLARATIVE_ENTITY_PROPERTY_STATE_PHRASE);
    createEReference(declarativeEntityPropertyStatePhraseEClass, DECLARATIVE_ENTITY_PROPERTY_STATE_PHRASE__PROPERTY);
    createEReference(declarativeEntityPropertyStatePhraseEClass, DECLARATIVE_ENTITY_PROPERTY_STATE_PHRASE__ENTITY);
    createEReference(declarativeEntityPropertyStatePhraseEClass, DECLARATIVE_ENTITY_PROPERTY_STATE_PHRASE__VALUE);
    createEReference(declarativeEntityPropertyStatePhraseEClass, DECLARATIVE_ENTITY_PROPERTY_STATE_PHRASE__VALUES);

    imperativeEntityPropertyStatePhraseEClass = createEClass(IMPERATIVE_ENTITY_PROPERTY_STATE_PHRASE);
    createEReference(imperativeEntityPropertyStatePhraseEClass, IMPERATIVE_ENTITY_PROPERTY_STATE_PHRASE__PROPERTY);
    createEReference(imperativeEntityPropertyStatePhraseEClass, IMPERATIVE_ENTITY_PROPERTY_STATE_PHRASE__ENTITY);
    createEReference(imperativeEntityPropertyStatePhraseEClass, IMPERATIVE_ENTITY_PROPERTY_STATE_PHRASE__PROPERTY_VALUE);

    simpleValueEClass = createEClass(SIMPLE_VALUE);

    stringValueEClass = createEClass(STRING_VALUE);
    createEAttribute(stringValueEClass, STRING_VALUE__VALUE);

    intValueEClass = createEClass(INT_VALUE);
    createEAttribute(intValueEClass, INT_VALUE__VALUE);

    doubleValueEClass = createEClass(DOUBLE_VALUE);
    createEAttribute(doubleValueEClass, DOUBLE_VALUE__VALUE);

    declarativeActionPhraseEClass = createEClass(DECLARATIVE_ACTION_PHRASE);

    imperativeActionPhraseEClass = createEClass(IMPERATIVE_ACTION_PHRASE);

    verbActionEClass = createEClass(VERB_ACTION);
    createEReference(verbActionEClass, VERB_ACTION__ACTION);
    createEReference(verbActionEClass, VERB_ACTION__ENTITY);
    createEReference(verbActionEClass, VERB_ACTION__ENTITY2);
    createEReference(verbActionEClass, VERB_ACTION__ENTITY3);

    declarativeEntityActionEClass = createEClass(DECLARATIVE_ENTITY_ACTION);
    createEReference(declarativeEntityActionEClass, DECLARATIVE_ENTITY_ACTION__ENTITY_ACTION);
    createEReference(declarativeEntityActionEClass, DECLARATIVE_ENTITY_ACTION__ACTION_DEF);
    createEReference(declarativeEntityActionEClass, DECLARATIVE_ENTITY_ACTION__ENTITY_REF);
    createEReference(declarativeEntityActionEClass, DECLARATIVE_ENTITY_ACTION__PROPERTY_REF);

    imperativeEntityActionEClass = createEClass(IMPERATIVE_ENTITY_ACTION);
    createEReference(imperativeEntityActionEClass, IMPERATIVE_ENTITY_ACTION__ENTITY_ACTION);
    createEAttribute(imperativeEntityActionEClass, IMPERATIVE_ENTITY_ACTION__ADVERB);
    createEReference(imperativeEntityActionEClass, IMPERATIVE_ENTITY_ACTION__ACTION_DEF);
    createEReference(imperativeEntityActionEClass, IMPERATIVE_ENTITY_ACTION__PROPERTY_REF);

    propertyRefEClass = createEClass(PROPERTY_REF);
    createEAttribute(propertyRefEClass, PROPERTY_REF__PROPERTYREF);
    createEReference(propertyRefEClass, PROPERTY_REF__PROPERTY);
    createEReference(propertyRefEClass, PROPERTY_REF__PROPERTY_VALUE);
    createEReference(propertyRefEClass, PROPERTY_REF__PROPERY_VALUE2);
    createEReference(propertyRefEClass, PROPERTY_REF__PROPERY2);

    imperativePropertyRefEClass = createEClass(IMPERATIVE_PROPERTY_REF);
    createEAttribute(imperativePropertyRefEClass, IMPERATIVE_PROPERTY_REF__PROPERTYREF);
    createEReference(imperativePropertyRefEClass, IMPERATIVE_PROPERTY_REF__PROPERTY);
    createEReference(imperativePropertyRefEClass, IMPERATIVE_PROPERTY_REF__PROPERTY_VALUE);
    createEReference(imperativePropertyRefEClass, IMPERATIVE_PROPERTY_REF__PROPERY_VALUE2);
    createEReference(imperativePropertyRefEClass, IMPERATIVE_PROPERTY_REF__PROPERY2);

    declarativeActionRefEClass = createEClass(DECLARATIVE_ACTION_REF);
    createEReference(declarativeActionRefEClass, DECLARATIVE_ACTION_REF__VERB);
    createEReference(declarativeActionRefEClass, DECLARATIVE_ACTION_REF__ARGUMENT);
    createEAttribute(declarativeActionRefEClass, DECLARATIVE_ACTION_REF__PREPOSITION);
    createEReference(declarativeActionRefEClass, DECLARATIVE_ACTION_REF__ENTITY);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    declarativeEntityPropertyStatePhraseEClass.getESuperTypes().add(this.getDeclarativeStatePhrase());
    stringValueEClass.getESuperTypes().add(this.getSimpleValue());
    intValueEClass.getESuperTypes().add(this.getSimpleValue());
    doubleValueEClass.getESuperTypes().add(this.getSimpleValue());
    verbActionEClass.getESuperTypes().add(this.getDeclarativeActionPhrase());
    declarativeEntityActionEClass.getESuperTypes().add(this.getDeclarativeActionPhrase());
    imperativeEntityActionEClass.getESuperTypes().add(this.getImperativeActionPhrase());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModel_Name(), ecorePackage.getEString(), "name", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_ModelRefs(), this.getModelRef(), null, "modelRefs", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_DeclarativeEntityDef(), this.getDeclarativeEntityDef(), null, "declarativeEntityDef", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_ImperativeEntityDef(), this.getImperativeEntityDef(), null, "imperativeEntityDef", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Scenarios(), this.getScenario(), null, "scenarios", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelRefEClass, ModelRef.class, "ModelRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModelRef_ModelRef(), this.getModel(), null, "modelRef", null, 0, 1, ModelRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeEntityDefEClass, DeclarativeEntityDef.class, "DeclarativeEntityDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDeclarativeEntityDef_Name(), ecorePackage.getEString(), "name", null, 0, 1, DeclarativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityDef_SuperEntities(), this.getDeclarativeEntityDef(), null, "superEntities", null, 0, -1, DeclarativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityDef_Actions(), this.getActionDef(), null, "actions", null, 0, -1, DeclarativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityDef_States(), this.getStateDef(), null, "states", null, 0, -1, DeclarativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityDef_Properties(), this.getPropertyDef(), null, "properties", null, 0, -1, DeclarativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeEntityDefEClass, ImperativeEntityDef.class, "ImperativeEntityDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImperativeEntityDef_Name(), ecorePackage.getEString(), "name", null, 0, 1, ImperativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeEntityDef_SuperEntities(), this.getImperativeEntityDef(), null, "superEntities", null, 0, -1, ImperativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeEntityDef_Actions(), this.getImperativeActionDef(), null, "actions", null, 0, -1, ImperativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeEntityDef_States(), this.getImperativeStateDef(), null, "states", null, 0, -1, ImperativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeEntityDef_Properties(), this.getImperativePropertyDef(), null, "properties", null, 0, -1, ImperativeEntityDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeActionDefEClass, ImperativeActionDef.class, "ImperativeActionDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImperativeActionDef_Name(), ecorePackage.getEString(), "name", null, 0, 1, ImperativeActionDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(actionDefEClass, ActionDef.class, "ActionDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getActionDef_Name(), ecorePackage.getEString(), "name", null, 0, 1, ActionDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stateDefEClass, StateDef.class, "StateDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStateDef_Postive(), this.getStateName(), null, "postive", null, 0, 1, StateDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStateDef_Negative(), this.getStateName(), null, "negative", null, 0, 1, StateDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stateNameEClass, StateName.class, "StateName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStateName_Name(), ecorePackage.getEString(), "name", null, 0, 1, StateName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStateName_Name2(), ecorePackage.getEString(), "name2", null, 0, 1, StateName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStateName_Name3(), ecorePackage.getEString(), "name3", null, 0, 1, StateName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(propertyDefEClass, PropertyDef.class, "PropertyDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPropertyDef_Name(), ecorePackage.getEString(), "name", null, 0, 1, PropertyDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPropertyDef_Plural(), ecorePackage.getEBoolean(), "plural", null, 0, 1, PropertyDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeStateDefEClass, ImperativeStateDef.class, "ImperativeStateDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeStateDef_Postive(), this.getImperativeStateName(), null, "postive", null, 0, 1, ImperativeStateDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeStateDef_Negative(), this.getImperativeStateName(), null, "negative", null, 0, 1, ImperativeStateDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeStateNameEClass, ImperativeStateName.class, "ImperativeStateName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeStateName_ImpStatName(), this.getStateName(), null, "impStatName", null, 0, 1, ImperativeStateName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativePropertyDefEClass, ImperativePropertyDef.class, "ImperativePropertyDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImperativePropertyDef_Name(), ecorePackage.getEString(), "name", null, 0, 1, ImperativePropertyDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getImperativePropertyDef_Plural(), ecorePackage.getEBoolean(), "plural", null, 0, 1, ImperativePropertyDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeScenarioEClass, ImperativeScenario.class, "ImperativeScenario", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeScenario_PreState(), this.getImperativeScenarioState(), null, "preState", null, 0, 1, ImperativeScenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeScenario_Action(), this.getImperativeScenarioAction(), null, "action", null, 0, 1, ImperativeScenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeScenario_PostState(), this.getImperativeScenarioState(), null, "postState", null, 0, 1, ImperativeScenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(scenarioEClass, Scenario.class, "Scenario", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getScenario_Name(), ecorePackage.getEString(), "name", null, 0, 1, Scenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getScenario_PreStateE(), this.getDeclarativeScenarioState(), null, "preStateE", null, 0, 1, Scenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getScenario_Imperative1(), this.getImperativeScenario(), null, "imperative1", null, 0, 1, Scenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getScenario_ActionE(), this.getDeclarativeScenarioAction(), null, "actionE", null, 0, 1, Scenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getScenario_Imperative2(), this.getImperativeScenario(), null, "imperative2", null, 0, 1, Scenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getScenario_PreStateE1(), this.getDeclarativeScenarioState(), null, "preStateE1", null, 0, 1, Scenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getScenario_Imperative3(), this.getImperativeScenario(), null, "imperative3", null, 0, 1, Scenario.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeScenarioStateEClass, DeclarativeScenarioState.class, "DeclarativeScenarioState", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclarativeScenarioState_States(), this.getDeclarativeStatePhrase(), null, "states", null, 0, -1, DeclarativeScenarioState.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeScenarioStateEClass, ImperativeScenarioState.class, "ImperativeScenarioState", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeScenarioState_States(), this.getImperativeStatePhrase(), null, "states", null, 0, -1, ImperativeScenarioState.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeScenarioActionEClass, DeclarativeScenarioAction.class, "DeclarativeScenarioAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclarativeScenarioAction_Actions(), this.getDeclarativeActionPhrase(), null, "actions", null, 0, -1, DeclarativeScenarioAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeScenarioActionEClass, ImperativeScenarioAction.class, "ImperativeScenarioAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeScenarioAction_Actions(), this.getImperativeActionPhrase(), null, "actions", null, 0, -1, ImperativeScenarioAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeStatePhraseEClass, DeclarativeStatePhrase.class, "DeclarativeStatePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclarativeStatePhrase_Esp(), this.getDeclarativeEntityStatePhrase(), null, "esp", null, 0, 1, DeclarativeStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeStatePhraseEClass, ImperativeStatePhrase.class, "ImperativeStatePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeStatePhrase_Epsp(), this.getImperativeEntityPropertyStatePhrase(), null, "epsp", null, 0, 1, ImperativeStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeStatePhrase_Esp(), this.getImperativeEntityStatePhrase(), null, "esp", null, 0, 1, ImperativeStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeEntityRefEClass, DeclarativeEntityRef.class, "DeclarativeEntityRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclarativeEntityRef_Entity(), this.getDeclarativeEntityDef(), null, "entity", null, 0, 1, DeclarativeEntityRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDeclarativeEntityRef_Name(), ecorePackage.getEString(), "name", null, 0, 1, DeclarativeEntityRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeEntityRefEClass, ImperativeEntityRef.class, "ImperativeEntityRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeEntityRef_Entity(), this.getImperativeEntityDef(), null, "entity", null, 0, 1, ImperativeEntityRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getImperativeEntityRef_Name(), ecorePackage.getEString(), "name", null, 0, 1, ImperativeEntityRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeEntityStatePhraseEClass, DeclarativeEntityStatePhrase.class, "DeclarativeEntityStatePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclarativeEntityStatePhrase_Property(), this.getPropertyDef(), null, "property", null, 0, 1, DeclarativeEntityStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityStatePhrase_Entity(), this.getDeclarativeEntityRef(), null, "entity", null, 0, 1, DeclarativeEntityStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityStatePhrase_State(), this.getStateName(), null, "state", null, 0, 1, DeclarativeEntityStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeEntityStatePhraseEClass, ImperativeEntityStatePhrase.class, "ImperativeEntityStatePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeEntityStatePhrase_Entity(), this.getImperativeEntityRef(), null, "entity", null, 0, 1, ImperativeEntityStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeEntityStatePhrase_State(), this.getImperativeStateName(), null, "state", null, 0, 1, ImperativeEntityStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeEntityPropertyStatePhraseEClass, DeclarativeEntityPropertyStatePhrase.class, "DeclarativeEntityPropertyStatePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclarativeEntityPropertyStatePhrase_Property(), this.getPropertyDef(), null, "property", null, 0, 1, DeclarativeEntityPropertyStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityPropertyStatePhrase_Entity(), this.getDeclarativeEntityRef(), null, "entity", null, 0, 1, DeclarativeEntityPropertyStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityPropertyStatePhrase_Value(), this.getSimpleValue(), null, "value", null, 0, 1, DeclarativeEntityPropertyStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityPropertyStatePhrase_Values(), this.getSimpleValue(), null, "values", null, 0, -1, DeclarativeEntityPropertyStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeEntityPropertyStatePhraseEClass, ImperativeEntityPropertyStatePhrase.class, "ImperativeEntityPropertyStatePhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeEntityPropertyStatePhrase_Property(), this.getImperativePropertyDef(), null, "property", null, 0, 1, ImperativeEntityPropertyStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeEntityPropertyStatePhrase_Entity(), this.getImperativeEntityRef(), null, "entity", null, 0, 1, ImperativeEntityPropertyStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeEntityPropertyStatePhrase_PropertyValue(), this.getStringValue(), null, "propertyValue", null, 0, 1, ImperativeEntityPropertyStatePhrase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(simpleValueEClass, SimpleValue.class, "SimpleValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(stringValueEClass, StringValue.class, "StringValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStringValue_Value(), ecorePackage.getEString(), "value", null, 0, 1, StringValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(intValueEClass, IntValue.class, "IntValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIntValue_Value(), ecorePackage.getEInt(), "value", null, 0, 1, IntValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(doubleValueEClass, DoubleValue.class, "DoubleValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDoubleValue_Value(), ecorePackage.getEDouble(), "value", null, 0, 1, DoubleValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeActionPhraseEClass, DeclarativeActionPhrase.class, "DeclarativeActionPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(imperativeActionPhraseEClass, ImperativeActionPhrase.class, "ImperativeActionPhrase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(verbActionEClass, VerbAction.class, "VerbAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getVerbAction_Action(), this.getDeclarativeActionRef(), null, "action", null, 0, 1, VerbAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVerbAction_Entity(), this.getDeclarativeEntityDef(), null, "entity", null, 0, 1, VerbAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVerbAction_Entity2(), this.getDeclarativeEntityRef(), null, "entity2", null, 0, 1, VerbAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVerbAction_Entity3(), this.getDeclarativeEntityRef(), null, "entity3", null, 0, 1, VerbAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeEntityActionEClass, DeclarativeEntityAction.class, "DeclarativeEntityAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclarativeEntityAction_EntityAction(), this.getDeclarativeEntityRef(), null, "entityAction", null, 0, 1, DeclarativeEntityAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityAction_ActionDef(), this.getActionDef(), null, "actionDef", null, 0, 1, DeclarativeEntityAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityAction_EntityRef(), this.getDeclarativeEntityRef(), null, "entityRef", null, 0, 1, DeclarativeEntityAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeEntityAction_PropertyRef(), this.getPropertyRef(), null, "propertyRef", null, 0, 1, DeclarativeEntityAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativeEntityActionEClass, ImperativeEntityAction.class, "ImperativeEntityAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImperativeEntityAction_EntityAction(), this.getImperativeEntityRef(), null, "entityAction", null, 0, 1, ImperativeEntityAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getImperativeEntityAction_Adverb(), ecorePackage.getEString(), "adverb", null, 0, 1, ImperativeEntityAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeEntityAction_ActionDef(), this.getImperativeActionDef(), null, "actionDef", null, 0, 1, ImperativeEntityAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativeEntityAction_PropertyRef(), this.getImperativePropertyRef(), null, "propertyRef", null, 0, 1, ImperativeEntityAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(propertyRefEClass, PropertyRef.class, "PropertyRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPropertyRef_Propertyref(), ecorePackage.getEString(), "propertyref", null, 0, 1, PropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPropertyRef_Property(), this.getPropertyDef(), null, "property", null, 0, 1, PropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPropertyRef_PropertyValue(), this.getStringValue(), null, "propertyValue", null, 0, 1, PropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPropertyRef_ProperyValue2(), this.getStringValue(), null, "properyValue2", null, 0, 1, PropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPropertyRef_Propery2(), this.getPropertyDef(), null, "propery2", null, 0, 1, PropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imperativePropertyRefEClass, ImperativePropertyRef.class, "ImperativePropertyRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImperativePropertyRef_Propertyref(), ecorePackage.getEString(), "propertyref", null, 0, 1, ImperativePropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativePropertyRef_Property(), this.getImperativePropertyDef(), null, "property", null, 0, 1, ImperativePropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativePropertyRef_PropertyValue(), this.getStringValue(), null, "propertyValue", null, 0, 1, ImperativePropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativePropertyRef_ProperyValue2(), this.getStringValue(), null, "properyValue2", null, 0, 1, ImperativePropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImperativePropertyRef_Propery2(), this.getImperativePropertyDef(), null, "propery2", null, 0, 1, ImperativePropertyRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declarativeActionRefEClass, DeclarativeActionRef.class, "DeclarativeActionRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclarativeActionRef_Verb(), this.getActionDef(), null, "verb", null, 0, 1, DeclarativeActionRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeActionRef_Argument(), this.getSimpleValue(), null, "argument", null, 0, 1, DeclarativeActionRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDeclarativeActionRef_Preposition(), ecorePackage.getEString(), "preposition", null, 0, 1, DeclarativeActionRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDeclarativeActionRef_Entity(), this.getDeclarativeEntityDef(), null, "entity", null, 0, 1, DeclarativeActionRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //BddDslPackageImpl
